title: Typophile (the return)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
